- name: Create the backup script
  become: yes
  template:
    src: "templates/backup.sh.jinja2"
    dest: "{{ PROJECT_PATH }}/scripts/backup.sh"
    owner: ubuntu
    mode: 0741

- name: Creates backups dir
  file:
    path: "{{ BACKUPS_DIR }}"
    state: directory


- name: fire the backup cron
  cron:
    name: "backup"
    minute: "0"
    hour: "19"
    user: "ubuntu"
    job: "{{ PROJECT_PATH }}/scripts/backup.sh"
