# Generated by Django 2.1.5 on 2019-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0001_switch-to-custom-user-model")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preview_mode",
            field=models.BooleanField(default=False),
        )
    ]
