# Generated by Django 2.1.7 on 2019-03-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="VersionAuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_to_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "now_published",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="now_published_versions",
                        to="ncdr.Version",
                    ),
                ),
                (
                    "previous_published",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_published_versions",
                        to="ncdr.Version",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ncdr.Version",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="versionauditlog",
            unique_together={
                ("created_at", "version", "previous_published", "now_published")
            },
        ),
    ]
