# Generated by Django 2.1.7 on 2019-02-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0002_move-profile-field-onto-user")]

    state_operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("datetime", "datetime"),
                            ("date", "date"),
                            ("int", "int"),
                            ("bigint", "bigint"),
                            ("varchar(1)", "varchar(1)"),
                            ("varchar(2)", "varchar(2)"),
                            ("varchar(3)", "varchar(3)"),
                            ("varchar(4)", "varchar(4)"),
                            ("varchar(5)", "varchar(5)"),
                            ("varchar(6)", "varchar(6)"),
                            ("varchar(7)", "varchar(7)"),
                            ("varchar(8)", "varchar(8)"),
                            ("varchar(9)", "varchar(9)"),
                            ("varchar(10)", "varchar(10)"),
                            ("varchar(11)", "varchar(11)"),
                            ("varchar(12)", "varchar(12)"),
                            ("varchar(13)", "varchar(13)"),
                            ("varchar(14)", "varchar(14)"),
                            ("varchar(15)", "varchar(15)"),
                            ("varchar(16)", "varchar(16)"),
                            ("varchar(17)", "varchar(17)"),
                            ("varchar(18)", "varchar(18)"),
                            ("varchar(19)", "varchar(19)"),
                            ("varchar(20)", "varchar(20)"),
                            ("varchar(50)", "varchar(50)"),
                            ("varchar(100)", "varchar(100)"),
                        ],
                        max_length=255,
                    ),
                ),
                ("derivation", models.TextField(blank=True, default="")),
                (
                    "technical_check",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_derived_item",
                    models.NullBooleanField(
                        default=False, verbose_name="Is the item derived?"
                    ),
                ),
                ("definition_id", models.IntegerField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("created_date_ext", models.DateField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("published", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "Column", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(default="")),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DataElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(default="")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Grouping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to="ncdr.Database",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(default="")),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "is_table",
                    models.BooleanField(
                        choices=[(True, "Table"), (False, "View")],
                        default=True,
                        verbose_name="Table or View",
                    ),
                ),
                (
                    "date_range",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="ncdr.Schema",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="dataelement",
            name="grouping",
            field=models.ManyToManyField(to="ncdr.Grouping"),
        ),
        migrations.AddField(
            model_name="column",
            name="data_element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ncdr.DataElement",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ncdr.Table"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table", unique_together={("name", "schema")}
        ),
        migrations.AlterUniqueTogether(
            name="schema", unique_together={("name", "database")}
        ),
        migrations.AlterUniqueTogether(
            name="column",
            unique_together={
                ("name", "table", "data_element", "is_derived_item", "link")
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
