# Generated by Django 2.1.7 on 2019-03-04 13:48

from django.db import migrations, models
import ncdr.models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0002_add_audit_log")]

    operations = [
        migrations.AddField(
            model_name="version",
            name="db_structure",
            field=models.FileField(null=True, upload_to=ncdr.models.versioned_path),
        ),
        migrations.AddField(
            model_name="version",
            name="definitions",
            field=models.FileField(null=True, upload_to=ncdr.models.versioned_path),
        ),
        migrations.AddField(
            model_name="version",
            name="grouping_mapping",
            field=models.FileField(null=True, upload_to=ncdr.models.versioned_path),
        ),
        migrations.AddField(
            model_name="version",
            name="last_process_at",
            field=models.DateTimeField(null=True),
        ),
    ]
