# Generated by Django 2.1.7 on 2019-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0004_add_file_and_processing_fields")]

    operations = [
        migrations.AddField(
            model_name="version",
            name="files_hash",
            field=models.TextField(null=True, unique=True),
        )
    ]
