# Generated by Django 2.1.7 on 2019-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0005_add_files_hash_to_version")]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="author",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="data_type",
            field=models.TextField(
                choices=[
                    ("datetime", "datetime"),
                    ("date", "date"),
                    ("int", "int"),
                    ("bigint", "bigint"),
                    ("varchar(1)", "varchar(1)"),
                    ("varchar(2)", "varchar(2)"),
                    ("varchar(3)", "varchar(3)"),
                    ("varchar(4)", "varchar(4)"),
                    ("varchar(5)", "varchar(5)"),
                    ("varchar(6)", "varchar(6)"),
                    ("varchar(7)", "varchar(7)"),
                    ("varchar(8)", "varchar(8)"),
                    ("varchar(9)", "varchar(9)"),
                    ("varchar(10)", "varchar(10)"),
                    ("varchar(11)", "varchar(11)"),
                    ("varchar(12)", "varchar(12)"),
                    ("varchar(13)", "varchar(13)"),
                    ("varchar(14)", "varchar(14)"),
                    ("varchar(15)", "varchar(15)"),
                    ("varchar(16)", "varchar(16)"),
                    ("varchar(17)", "varchar(17)"),
                    ("varchar(18)", "varchar(18)"),
                    ("varchar(19)", "varchar(19)"),
                    ("varchar(20)", "varchar(20)"),
                    ("varchar(50)", "varchar(50)"),
                    ("varchar(100)", "varchar(100)"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="column", name="name", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="column",
            name="technical_check",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="database",
            name="owner",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataelement", name="name", field=models.TextField(unique=True)
        ),
        migrations.AlterField(
            model_name="grouping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grouping", name="name", field=models.TextField(unique=True)
        ),
        migrations.AlterField(
            model_name="table",
            name="date_range",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="table", name="name", field=models.TextField()
        ),
    ]
