# Generated by Django 2.1.7 on 2019-02-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0006_link_version_to_database_and_user")]

    operations = [
        migrations.AlterModelOptions(name="version", options={"get_latest_by": "pk"}),
        migrations.RemoveField(model_name="column", name="published"),
        migrations.AddField(
            model_name="version",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="current_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ncdr.Version"
            ),
        ),
    ]
