# Generated by Django 2.1.7 on 2019-06-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0007_remove_technical_check")]

    operations = [
        migrations.AlterModelOptions(
            name="database", options={"ordering": ["display_name"]}
        ),
        migrations.AlterModelOptions(
            name="dataelement",
            options={"ordering": ["name"], "verbose_name_plural": "Data Elements"},
        ),
    ]
