# Generated by Django 2.1.7 on 2019-02-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0007_move_published_to_version")]

    operations = [migrations.RemoveField(model_name="user", name="preview_mode")]
