# Generated by Django 2.1.7 on 2019-06-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0008_auto_20190603_2047")]

    operations = [
        migrations.AlterModelOptions(
            name="database",
            options={"ordering": ["display_name"], "verbose_name": "Database"},
        ),
        migrations.AlterModelOptions(
            name="dataelement",
            options={"ordering": ["name"], "verbose_name": "Data Element"},
        ),
        migrations.AlterModelOptions(
            name="grouping", options={"ordering": ["name"], "verbose_name": "Grouping"}
        ),
        migrations.AlterModelOptions(
            name="schema", options={"ordering": ["name"], "verbose_name": "Schema"}
        ),
        migrations.AlterModelOptions(
            name="table", options={"ordering": ["name"], "verbose_name": "Table"}
        ),
    ]
