# Generated by Django 2.1.7 on 2019-02-28 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0008_remove_preview_mode")]

    operations = [
        migrations.AddField(
            model_name="version",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="version",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
