# Generated by Django 2.1.7 on 2019-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0009_auto_20190605_0927")]

    operations = [
        migrations.AlterField(
            model_name="dataelement", name="name", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="dataelement",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="grouping", name="name", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="grouping",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
