# Generated by Django 2.1.7 on 2019-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0010_make_user_current_version_nullable")]

    operations = [
        migrations.AlterField(
            model_name="database", name="name", field=models.TextField()
        ),
        migrations.AlterUniqueTogether(
            name="database", unique_together={("name", "version")}
        ),
    ]
