# Generated by Django 2.1.7 on 2021-01-05 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0011_auto_20190917_1748")]

    operations = [
        migrations.CreateModel(
            name="ColumnImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="imgs")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ColumnImageRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("database_name", models.TextField(default="")),
                ("schema_name", models.TextField(default="")),
                ("table_name", models.TextField(default="")),
                ("column_name", models.TextField(default="")),
                (
                    "column_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ncdr.ColumnImage",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="columnimagerelation",
            unique_together={
                (
                    "column_image",
                    "database_name",
                    "schema_name",
                    "table_name",
                    "column_name",
                )
            },
        ),
    ]
