# Generated by Django 2.1.7 on 2021-03-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0011_auto_20190917_1748")]

    operations = [
        migrations.RemoveField(model_name="version", name="created_by"),
        migrations.RemoveField(model_name="version", name="db_structure"),
        migrations.RemoveField(model_name="version", name="definitions"),
        migrations.RemoveField(model_name="version", name="files_hash"),
        migrations.RemoveField(model_name="version", name="grouping_mapping"),
        migrations.RemoveField(model_name="version", name="last_process_at"),
    ]
