# Generated by Django 2.1.11 on 2020-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0011_auto_20190917_1748")]

    operations = [
        migrations.AddField(
            model_name="version",
            name="version_type",
            field=models.TextField(
                choices=[("Metrics", "Metrics"), ("NCDR", "NCDR")], default="NCDR"
            ),
            preserve_default=False,
        )
    ]
