# Generated by Django 2.1.7 on 2021-01-08 10:35

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0012_auto_20210105_1135")]

    operations = [
        migrations.AlterField(
            model_name="columnimage",
            name="image",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="imgs",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "svg", "gif"]
                    )
                ],
            ),
        )
    ]
