# Generated by Django 2.1.11 on 2020-01-30 14:36

from django.db import migrations, models
import ncdr.models


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0012_version_version_type")]

    operations = [
        migrations.AddField(
            model_name="version",
            name="metrics",
            field=models.FileField(
                blank=True, null=True, upload_to=ncdr.models.versioned_path
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="db_structure",
            field=models.FileField(
                blank=True, null=True, upload_to=ncdr.models.versioned_path
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="definitions",
            field=models.FileField(
                blank=True, null=True, upload_to=ncdr.models.versioned_path
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="grouping_mapping",
            field=models.FileField(
                blank=True, null=True, upload_to=ncdr.models.versioned_path
            ),
        ),
    ]
