# Generated by Django 2.1.11 on 2020-01-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0013_auto_20200130_1436")]

    operations = [
        migrations.RenameField(
            model_name="version", old_name="metrics", new_name="metrics_file"
        )
    ]
