# Generated by Django 2.1.7 on 2021-07-05 13:46

import datetime
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0014_auto_20210108_1035")]

    operations = [
        migrations.AddField(
            model_name="version",
            name="upstream_updated_ts",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 7, 5, 13, 46, 30, 947903, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="columnimage",
            name="image",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="imgs",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["gif", "jpg", "jpeg", "png", "svg"]
                    )
                ],
            ),
        ),
    ]
