# Generated by Django 2.1.11 on 2020-01-30 18:14

from django.db import migrations


def create_version(apps, schema_editor):
    Version = apps.get_model("ncdr", "Version")
    Version.objects.filter(version_type=None).update(version_type="NCDR")

    version, _ = Version.objects.get_or_create(
        is_published=True, version_type="Metrics"
    )
    Metric = apps.get_model("metrics", "Metric")
    Metric.objects.filter(version=None).update(version=version)


def delete_version(apps, schema_editor):
    Version = apps.get_model("ncdr", "Version")
    Version.objects.filter(is_published=True, version_type="Metrics").delete()
    Version.objects.filter(version_type="NCDR").update(version_type=None)


class Migration(migrations.Migration):

    dependencies = [("ncdr", "0014_auto_20200130_1535")]

    operations = [migrations.RunPython(create_version, reverse_code=delete_version)]
