- name: Creates AWS dir
  file:
    path: /home/ubuntu/.aws
    state: directory

- name: create AWS credentials
  template:
    src: templates/aws_credentials.ini
    dest: /home/ubuntu/.aws/credentials

- name: create AWS config
  template:
    src: templates/aws_config.ini
    dest: /home/ubuntu/.aws/config
