# Generated by Django 2.1.7 on 2019-06-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("metrics", "0002_metric_subclasses_ncdr_model")]

    operations = [
        migrations.AlterModelOptions(name="metric", options={"verbose_name": "Metric"})
    ]
