# Generated by Django 2.1.7 on 2019-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("metrics", "0003_auto_20190605_0927")]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(model_name="metric", name="theme"),
        migrations.DeleteModel(name="Theme"),
        migrations.AddField(
            model_name="metric",
            name="topic_set",
            field=models.ManyToManyField(to="metrics.Topic"),
        ),
    ]
