# Generated by Django 2.1.7 on 2019-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("metrics", "0004_auto_20191029_1500")]

    operations = [
        migrations.CreateModel(
            name="MetricLead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="TeamLead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
    ]
