# Generated by Django 2.1.7 on 2019-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("metrics", "0005_auto_20190808_1440")]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="desired_direction",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metric",
            name="organisation_type",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metric",
            name="strategic_origin",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
