# Generated by Django 2.1.7 on 2019-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("metrics", "0006_auto_20191029_1505")]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        )
    ]
