# Generated by Django 2.1.7 on 2019-10-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("metrics", "0007_topic_slug")]

    operations = [
        migrations.AlterModelOptions(
            name="metric",
            options={"ordering": ["display_name"], "verbose_name": "Metric"},
        )
    ]
