# Generated by Django 2.1.11 on 2020-01-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("metrics", "0008_auto_20191029_1722")]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metrics.Report",
            ),
        )
    ]
