# Generated by Django 2.1.11 on 2020-01-30 19:05

from django.db import migrations


def create_version(apps, schema_editor):
    Version = apps.get_model("ncdr", "Version")
    Version.objects.filter(version_type=None).update(version_type="NCDR")

    version, _ = Version.objects.get_or_create(
        is_published=True, version_type="Metrics"
    )
    Metric = apps.get_model("metrics", "Metric")
    Metric.objects.filter(version=None).update(version=version)


def delete_version(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("metrics", "0009_metric_version")]
    operations = [migrations.RunPython(create_version, reverse_code=delete_version)]
