# Generated by Django 2.1.11 on 2020-01-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("metrics", "0010_create_metrics_version")]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="ncdr.Version",
            ),
        )
    ]
