# Generated by Django 2.1.11 on 2020-01-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0011_auto_20200130_1907"),
        ("metrics", "0009_auto_20200106_1745"),
    ]

    operations = []
