---
- name: Things you want on servers generally
  become: yes
  user: ubuntu
  hosts: webserver
  gather_facts: no
  roles:
    - server

- name: Add the MSSQL drivers
  become: yes
  user: ubuntu
  hosts: webserver
  gather_facts: no
  roles:
    - mssql_odbc

- name: Make the server capable of running a standard Django deployment
  user: ubuntu
  hosts: webserver
  roles:
    - django

- name: Setup aws
  user: ubuntu
  hosts: webserver
  roles:
    - aws

- name: Make the server capable of running a standard Django deployment
  become: yes
  user: ubuntu
  hosts: webserver
  roles:
    - db

- name: Set up our project
  user: ubuntu
  hosts: webserver
  roles:
    - ncdr

- name: Set the project back ups
  user: ubuntu
  hosts: webserver
  roles:
    - restore

- name: Set the project back ups
  user: ubuntu
  hosts: webserver
  roles:
    - role: backup
      when: not DEV
