# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['data_dictionary_name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
    ]
