# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
