# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0002_auto_20171017_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
