# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0003_sitedescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['table', 'data_item']},
        ),
    ]
