# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0004_auto_20171018_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='data_dictionary_link',
            field=models.URLField(max_length=500),
        ),
    ]
