# Generated by Django 2.0 on 2017-12-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("csv_schema", "0004_auto_20171214_1410")]

    operations = [
        migrations.AlterModelOptions(name="mapping", options={"ordering": ["name"]})
    ]
