# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0005_auto_20171019_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='is_derived_item',
            field=models.NullBooleanField(default=False),
        ),
    ]
