# Generated by Django 2.0 on 2018-01-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("csv_schema", "0005_auto_20171214_1415")]

    operations = [migrations.DeleteModel(name="SiteDescription")]
