# Generated by Django 2.0 on 2018-01-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0007_database_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='owner',
        ),
    ]
