# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0007_auto_20171025_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='row',
            unique_together=set([('table', 'data_item')]),
        ),
    ]
