# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0008_auto_20171025_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionaryReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_schema.Row')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
