# Generated by Django 2.0 on 2018-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0009_auto_20180214_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapping',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
