# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0012_auto_20171103_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='table',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='table',
            name='is_table',
            field=models.BooleanField(default=True),
        ),
    ]
