# Generated by Django 2.0 on 2018-02-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0013_auto_20180227_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
