# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0013_auto_20171117_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
