# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0014_auto_20171117_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='derivation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='row',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
