# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csv_schema', '0014_auto_20171117_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='business_check',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='table',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='technical_check',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='table',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set([('name', 'database', 'version')]),
        ),
    ]
