# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0015_auto_20171120_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
