# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0015_auto_20171129_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='derivation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='row',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
