# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0016_auto_20171129_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Row',
            new_name='Column',
        ),
        migrations.RenameField(
            model_name='datadictionaryreference',
            old_name='row',
            new_name='column',
        ),
        migrations.AlterUniqueTogether(
            name='datadictionaryreference',
            unique_together=set([('column', 'name')]),
        ),
    ]
