# Generated by Django 2.0 on 2018-02-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0016_auto_20180228_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='grouping',
        ),
        migrations.AddField(
            model_name='dataelement',
            name='grouping',
            field=models.ManyToManyField(blank=True, null=True, to='csv_schema.Grouping'),
        ),
    ]
