# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0016_table_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name', 'published_date', 'created']},
        ),
        migrations.AddField(
            model_name='table',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
