# Generated by Django 2.0 on 2018-03-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0017_auto_20180228_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='is_derived_item',
            field=models.NullBooleanField(default=False, verbose_name='Is the item derived?'),
        ),
        migrations.AlterField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_schema.Table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_table',
            field=models.BooleanField(choices=[(True, 'Table'), (False, 'View')], default=True, verbose_name='Table or View'),
        ),
    ]
