# Generated by Django 2.0 on 2018-03-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0019_auto_20180323_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='grouping',
            field=models.ManyToManyField(to='csv_schema.Grouping'),
        ),
    ]
