# Generated by Django 2.0 on 2018-03-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_schema', '0021_auto_20180327_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouping',
            options={'ordering': ['name']},
        ),
    ]
