# Generated by Django 2.1.7 on 2019-02-15 09:43

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("csv_schema", "0027_alter_column_unique_together")]

    database_operations = [
        migrations.AlterModelTable("Column", "ncdr_column"),
        migrations.AlterModelTable("Database", "ncdr_database"),
        migrations.AlterModelTable("DataElement", "ncdr_dataelement"),
        migrations.AlterModelTable("Grouping", "ncdr_grouping"),
        migrations.AlterModelTable("Schema", "ncdr_schema"),
        migrations.AlterModelTable("Table", "ncdr_table"),
    ]

    state_operations = [
        migrations.DeleteModel("Column"),
        migrations.DeleteModel("Database"),
        migrations.DeleteModel("DataElement"),
        migrations.DeleteModel("Grouping"),
        migrations.DeleteModel("Schema"),
        migrations.DeleteModel("Table"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
